[2025-02-12T20:33:24.212+0000] {processor.py:186} INFO - Started process (PID=1141) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:33:24.213+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:33:24.217+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:33:24.217+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:33:26.811+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:33:26.805+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 13, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:33:26.820+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:33:26.837+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 2.632 seconds
[2025-02-12T20:33:57.599+0000] {processor.py:186} INFO - Started process (PID=1152) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:33:57.601+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:33:57.604+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:33:57.603+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:33:57.933+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:33:57.926+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 13, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:33:57.935+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:33:57.954+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.363 seconds
[2025-02-12T20:34:28.425+0000] {processor.py:186} INFO - Started process (PID=1163) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:34:28.426+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:34:28.429+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:34:28.429+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:34:28.775+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:34:28.768+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 13, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:34:28.777+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:34:28.802+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.383 seconds
[2025-02-12T20:34:59.052+0000] {processor.py:186} INFO - Started process (PID=1174) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:34:59.053+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:34:59.056+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:34:59.056+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:34:59.389+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:34:59.383+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 13, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:34:59.392+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:34:59.414+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.369 seconds
[2025-02-12T20:35:29.563+0000] {processor.py:186} INFO - Started process (PID=1185) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:35:29.564+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:35:29.567+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:35:29.566+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:35:29.907+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:35:29.899+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 13, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:35:29.909+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:35:29.935+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.379 seconds
[2025-02-12T20:36:00.094+0000] {processor.py:186} INFO - Started process (PID=1196) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:36:00.096+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:36:00.099+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:36:00.099+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:36:00.422+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:36:00.415+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 13, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:36:00.425+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:36:00.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.364 seconds
[2025-02-12T20:36:30.635+0000] {processor.py:186} INFO - Started process (PID=1207) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:36:30.636+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:36:30.639+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:36:30.639+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:36:30.973+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:36:30.966+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 13, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:36:30.975+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:36:30.995+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.367 seconds
[2025-02-12T20:37:01.192+0000] {processor.py:186} INFO - Started process (PID=1218) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:37:01.194+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:37:01.198+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:37:01.198+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:37:01.576+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:37:01.570+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 13, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:37:01.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:37:01.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.416 seconds
[2025-02-12T20:37:31.736+0000] {processor.py:186} INFO - Started process (PID=1229) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:37:31.738+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:37:31.741+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:37:31.740+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:37:32.065+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:37:32.058+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 13, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:37:32.068+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:37:32.092+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.364 seconds
[2025-02-12T20:38:02.252+0000] {processor.py:186} INFO - Started process (PID=1240) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:38:02.254+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:38:02.257+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:38:02.257+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:38:02.612+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:38:02.605+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 13, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:38:02.615+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:38:02.642+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.397 seconds
[2025-02-12T20:38:32.764+0000] {processor.py:186} INFO - Started process (PID=1251) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:38:32.766+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:38:32.768+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:38:32.768+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:38:33.111+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:38:33.104+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 13, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:38:33.113+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:38:33.139+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.382 seconds
[2025-02-12T20:39:03.194+0000] {processor.py:186} INFO - Started process (PID=1262) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:39:03.196+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:39:03.198+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:39:03.198+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:39:03.543+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:39:03.537+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 13, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:39:03.546+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:39:03.570+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.382 seconds
[2025-02-12T20:39:33.744+0000] {processor.py:186} INFO - Started process (PID=1273) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:39:33.746+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:39:33.749+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:39:33.748+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:39:34.109+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:39:34.102+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 13, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:39:34.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:39:34.137+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.400 seconds
[2025-02-12T20:40:04.252+0000] {processor.py:186} INFO - Started process (PID=1284) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:40:04.254+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:40:04.256+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:40:04.256+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:40:04.650+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:40:04.645+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 13, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:40:04.652+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:40:04.679+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.435 seconds
[2025-02-12T20:40:34.919+0000] {processor.py:186} INFO - Started process (PID=1295) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:40:34.921+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:40:34.924+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:40:34.924+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:40:35.286+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:40:35.268+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 13, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:40:35.289+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:40:35.330+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.417 seconds
[2025-02-12T20:41:05.496+0000] {processor.py:186} INFO - Started process (PID=1306) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:41:05.497+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:41:05.501+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:41:05.501+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:41:06.080+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:41:06.072+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 13, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:41:06.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:41:06.106+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.618 seconds
[2025-02-12T20:41:36.588+0000] {processor.py:186} INFO - Started process (PID=1317) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:41:36.589+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:41:36.594+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:41:36.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:41:36.977+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:41:36.973+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 13, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:41:36.979+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:41:36.995+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.418 seconds
[2025-02-12T20:42:07.071+0000] {processor.py:186} INFO - Started process (PID=1328) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:42:07.072+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:42:07.077+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:42:07.076+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:42:07.460+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:42:07.454+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:42:07.462+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:42:07.480+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.419 seconds
[2025-02-12T20:42:37.670+0000] {processor.py:186} INFO - Started process (PID=1339) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:42:37.671+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:42:37.674+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:42:37.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:42:38.041+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:42:38.034+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:42:38.044+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:42:38.065+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.403 seconds
[2025-02-12T20:43:08.156+0000] {processor.py:186} INFO - Started process (PID=1350) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:43:08.157+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:43:08.160+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:43:08.160+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:43:08.510+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:43:08.504+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:43:08.513+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:43:08.532+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.383 seconds
[2025-02-12T20:43:38.816+0000] {processor.py:186} INFO - Started process (PID=1361) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:43:38.818+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:43:38.821+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:43:38.820+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:43:39.159+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:43:39.152+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:43:39.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:43:39.186+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.377 seconds
[2025-02-12T20:44:09.412+0000] {processor.py:186} INFO - Started process (PID=1372) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:44:09.413+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:44:09.418+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:44:09.417+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:44:09.755+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:44:09.748+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:44:09.758+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:44:09.779+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.374 seconds
[2025-02-12T20:44:39.989+0000] {processor.py:186} INFO - Started process (PID=1383) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:44:39.990+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:44:39.993+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:44:39.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:44:40.321+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:44:40.315+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:44:40.324+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:44:40.348+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.366 seconds
[2025-02-12T20:45:10.533+0000] {processor.py:186} INFO - Started process (PID=1394) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:45:10.534+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:45:10.537+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:45:10.537+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:45:10.868+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:45:10.862+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:45:10.871+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:45:10.896+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.370 seconds
[2025-02-12T20:45:40.976+0000] {processor.py:186} INFO - Started process (PID=1405) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:45:40.977+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:45:40.981+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:45:40.981+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:45:41.338+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:45:41.331+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:45:41.341+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:45:41.361+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.394 seconds
[2025-02-12T20:46:11.427+0000] {processor.py:186} INFO - Started process (PID=1416) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:46:11.428+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:46:11.431+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:46:11.431+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:46:11.809+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:46:11.803+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:46:11.811+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:46:11.829+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.409 seconds
[2025-02-12T20:46:41.900+0000] {processor.py:186} INFO - Started process (PID=1427) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:46:41.901+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:46:41.904+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:46:41.903+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:46:42.400+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:46:42.393+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:46:42.402+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:46:42.421+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.528 seconds
[2025-02-12T20:47:12.583+0000] {processor.py:186} INFO - Started process (PID=1438) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:47:12.585+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:47:12.587+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:47:12.587+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:47:12.933+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:47:12.927+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:47:12.936+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:47:12.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.384 seconds
[2025-02-12T20:47:43.143+0000] {processor.py:186} INFO - Started process (PID=1449) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:47:43.145+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:47:43.148+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:47:43.147+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:47:43.545+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:47:43.540+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:47:43.548+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:47:43.573+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.437 seconds
[2025-02-12T20:48:13.692+0000] {processor.py:186} INFO - Started process (PID=1460) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:48:13.694+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:48:13.696+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:48:13.696+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:48:14.027+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:48:14.021+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:48:14.030+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:48:14.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.370 seconds
[2025-02-12T20:48:44.261+0000] {processor.py:186} INFO - Started process (PID=1471) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:48:44.262+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:48:44.266+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:48:44.265+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:48:44.603+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:48:44.596+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:48:44.605+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:48:44.630+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.378 seconds
[2025-02-12T20:49:14.774+0000] {processor.py:186} INFO - Started process (PID=1482) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:49:14.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:49:14.779+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:49:14.779+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:49:15.110+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:49:15.103+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:49:15.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:49:15.137+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.370 seconds
[2025-02-12T20:49:45.322+0000] {processor.py:186} INFO - Started process (PID=1493) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:49:45.323+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:49:45.326+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:49:45.325+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:49:45.839+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:49:45.832+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:49:45.842+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:49:45.859+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.544 seconds
[2025-02-12T20:50:16.683+0000] {processor.py:186} INFO - Started process (PID=1504) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:50:16.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:50:16.687+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:50:16.687+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:50:17.012+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:50:17.005+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:50:17.014+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:50:17.038+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.363 seconds
[2025-02-12T20:50:47.363+0000] {processor.py:186} INFO - Started process (PID=1515) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:50:47.364+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:50:47.367+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:50:47.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:50:47.700+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:50:47.694+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:50:47.703+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:50:47.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.367 seconds
[2025-02-12T20:51:17.829+0000] {processor.py:186} INFO - Started process (PID=1526) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:51:17.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:51:17.834+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:51:17.833+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:51:18.203+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:51:18.196+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:51:18.205+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:51:18.226+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.405 seconds
[2025-02-12T20:51:48.285+0000] {processor.py:186} INFO - Started process (PID=1537) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:51:48.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:51:48.289+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:51:48.289+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:51:48.657+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:51:48.652+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:51:48.659+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:51:48.686+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.408 seconds
[2025-02-12T20:52:18.812+0000] {processor.py:186} INFO - Started process (PID=1548) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:52:18.813+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:52:18.816+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:52:18.815+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:52:19.190+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:52:19.185+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:52:19.192+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:52:19.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.409 seconds
[2025-02-12T20:52:49.355+0000] {processor.py:186} INFO - Started process (PID=1559) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:52:49.357+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:52:49.360+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:52:49.359+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:52:49.953+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:52:49.948+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:52:49.956+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:52:49.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.634 seconds
[2025-02-12T20:53:20.896+0000] {processor.py:186} INFO - Started process (PID=1570) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:53:20.897+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:53:20.901+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:53:20.901+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:53:21.240+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:53:21.234+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:53:21.242+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:53:21.266+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.376 seconds
[2025-02-12T20:53:51.565+0000] {processor.py:186} INFO - Started process (PID=1581) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:53:51.567+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:53:51.570+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:53:51.569+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:53:51.976+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:53:51.971+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:53:51.978+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:53:51.997+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.441 seconds
[2025-02-12T20:54:22.140+0000] {processor.py:186} INFO - Started process (PID=1592) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:54:22.141+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:54:22.144+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:54:22.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:54:22.487+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:54:22.480+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:54:22.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:54:22.514+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.383 seconds
[2025-02-12T20:54:52.725+0000] {processor.py:186} INFO - Started process (PID=1603) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:54:52.727+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:54:52.729+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:54:52.729+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:54:53.066+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:54:53.059+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:54:53.069+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:54:53.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.370 seconds
[2025-02-12T20:55:23.232+0000] {processor.py:186} INFO - Started process (PID=1614) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:55:23.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:55:23.237+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:55:23.237+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:55:23.718+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:55:23.712+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:55:23.721+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:55:23.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.514 seconds
[2025-02-12T20:55:54.556+0000] {processor.py:186} INFO - Started process (PID=1625) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:55:54.557+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:55:54.560+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:55:54.560+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:55:55.030+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:55:55.023+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:55:55.032+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:55:55.054+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.505 seconds
[2025-02-12T20:56:25.184+0000] {processor.py:186} INFO - Started process (PID=1636) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:56:25.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:56:25.189+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:56:25.188+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:56:25.552+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:56:25.545+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:56:25.555+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:56:25.580+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.403 seconds
[2025-02-12T20:56:55.775+0000] {processor.py:186} INFO - Started process (PID=1647) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:56:55.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:56:55.779+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:56:55.778+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:56:56.124+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:56:56.117+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:56:56.126+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:56:56.145+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.378 seconds
[2025-02-12T20:57:26.412+0000] {processor.py:186} INFO - Started process (PID=1658) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:57:26.413+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:57:26.416+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:57:26.416+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:57:26.755+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:57:26.749+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:57:26.758+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:57:26.781+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.377 seconds
[2025-02-12T20:57:56.909+0000] {processor.py:186} INFO - Started process (PID=1669) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:57:56.911+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:57:56.913+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:57:56.913+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:57:57.253+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:57:57.247+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:57:57.255+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:57:57.276+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.373 seconds
[2025-02-12T20:58:27.352+0000] {processor.py:186} INFO - Started process (PID=1680) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:58:27.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:58:27.356+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:58:27.356+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:58:27.939+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:58:27.884+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:58:27.942+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:58:27.967+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.622 seconds
[2025-02-12T20:58:58.839+0000] {processor.py:186} INFO - Started process (PID=1691) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:58:58.840+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:58:58.845+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:58:58.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:58:59.424+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:58:59.420+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:58:59.426+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:58:59.448+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.620 seconds
[2025-02-12T20:59:29.518+0000] {processor.py:186} INFO - Started process (PID=1702) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:59:29.520+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T20:59:29.523+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:59:29.523+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:59:29.879+0000] {logging_mixin.py:190} INFO - [2025-02-12T20:59:29.873+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T20:59:29.882+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T20:59:29.901+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.390 seconds
[2025-02-12T21:00:00.040+0000] {processor.py:186} INFO - Started process (PID=1713) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:00:00.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:00:00.045+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:00:00.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:00:00.387+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:00:00.381+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 22, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:00:00.390+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:00:00.409+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.376 seconds
[2025-02-12T21:00:06.638+0000] {processor.py:186} INFO - Started process (PID=1722) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:00:06.639+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:00:06.642+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:00:06.642+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:00:07.099+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:00:07.094+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:00:07.102+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:00:07.120+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.491 seconds
[2025-02-12T21:00:37.554+0000] {processor.py:186} INFO - Started process (PID=1734) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:00:37.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:00:37.559+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:00:37.559+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:00:37.909+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:00:37.902+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:00:37.911+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:00:37.939+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.393 seconds
[2025-02-12T21:01:08.335+0000] {processor.py:186} INFO - Started process (PID=1746) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:01:08.336+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:01:08.338+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:01:08.338+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:01:08.850+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:01:08.843+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:01:08.853+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:01:08.870+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.542 seconds
[2025-02-12T21:01:39.217+0000] {processor.py:186} INFO - Started process (PID=1758) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:01:39.218+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:01:39.220+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:01:39.219+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:01:39.736+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:01:39.730+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:01:39.739+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:01:39.755+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.546 seconds
[2025-02-12T21:02:09.967+0000] {processor.py:186} INFO - Started process (PID=1773) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:02:09.972+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:02:09.978+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:02:09.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:02:10.804+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:02:10.797+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:02:10.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:02:10.836+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.904 seconds
[2025-02-12T21:02:40.988+0000] {processor.py:186} INFO - Started process (PID=1801) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:02:40.990+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:02:40.991+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:02:40.991+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:02:41.334+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:02:41.326+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:02:41.336+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:02:41.363+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.382 seconds
[2025-02-12T21:03:11.960+0000] {processor.py:186} INFO - Started process (PID=1813) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:03:11.962+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:03:11.965+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:03:11.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:03:12.338+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:03:12.329+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:03:12.340+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:03:12.359+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.409 seconds
[2025-02-12T21:03:42.766+0000] {processor.py:186} INFO - Started process (PID=1825) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:03:42.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:03:42.769+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:03:42.769+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:03:43.279+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:03:43.271+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:03:43.281+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:03:43.297+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.538 seconds
[2025-02-12T21:04:13.721+0000] {processor.py:186} INFO - Started process (PID=1853) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:04:13.722+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:04:13.726+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:04:13.726+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:04:14.317+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:04:14.310+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:04:14.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:04:14.342+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.633 seconds
[2025-02-12T21:04:44.709+0000] {processor.py:186} INFO - Started process (PID=1865) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:04:44.710+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:04:44.712+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:04:44.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:04:45.191+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:04:45.184+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:04:45.192+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:04:45.215+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.513 seconds
[2025-02-12T21:05:15.610+0000] {processor.py:186} INFO - Started process (PID=1877) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:05:15.611+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:05:15.613+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:05:15.613+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:05:16.096+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:05:16.089+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:05:16.099+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:05:16.120+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.517 seconds
[2025-02-12T21:05:47.000+0000] {processor.py:186} INFO - Started process (PID=1889) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:05:47.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:05:47.003+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:05:47.003+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:05:47.344+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:05:47.336+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:05:47.346+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:05:47.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.377 seconds
[2025-02-12T21:06:17.746+0000] {processor.py:186} INFO - Started process (PID=1901) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:06:17.747+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:06:17.749+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:06:17.748+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:06:18.106+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:06:18.098+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:06:18.109+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:06:18.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.388 seconds
[2025-02-12T21:06:48.524+0000] {processor.py:186} INFO - Started process (PID=1913) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:06:48.526+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:06:48.528+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:06:48.527+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:06:49.061+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:06:49.056+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:06:49.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:06:49.080+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.569 seconds
[2025-02-12T21:07:19.215+0000] {processor.py:186} INFO - Started process (PID=1925) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:07:19.217+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:07:19.219+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:07:19.218+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:07:19.750+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:07:19.743+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:07:19.753+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:07:19.769+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.561 seconds
[2025-02-12T21:07:50.581+0000] {processor.py:186} INFO - Started process (PID=1937) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:07:50.582+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:07:50.584+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:07:50.584+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:07:51.073+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:07:51.067+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:07:51.076+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:07:51.094+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.520 seconds
[2025-02-12T21:08:21.520+0000] {processor.py:186} INFO - Started process (PID=1949) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:08:21.521+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:08:21.523+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:08:21.522+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:08:22.117+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:08:22.112+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:08:22.119+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:08:22.134+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.621 seconds
[2025-02-12T21:08:52.330+0000] {processor.py:186} INFO - Started process (PID=1967) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:08:52.332+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:08:52.334+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:08:52.333+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:08:52.692+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:08:52.685+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:08:52.694+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:08:52.715+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.392 seconds
[2025-02-12T21:09:23.073+0000] {processor.py:186} INFO - Started process (PID=1995) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:09:23.074+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:09:23.076+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:09:23.075+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:09:23.592+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:09:23.584+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:09:23.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:09:23.620+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.555 seconds
[2025-02-12T21:09:54.017+0000] {processor.py:186} INFO - Started process (PID=2029) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:09:54.019+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:09:54.021+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:09:54.020+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:09:55.024+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:09:55.019+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:09:55.026+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:09:55.042+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 1.033 seconds
[2025-02-12T21:10:25.419+0000] {processor.py:186} INFO - Started process (PID=2041) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:10:25.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:10:25.422+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:10:25.422+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:10:25.903+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:10:25.898+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:10:25.905+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:10:25.922+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.512 seconds
[2025-02-12T21:10:56.711+0000] {processor.py:186} INFO - Started process (PID=2053) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:10:56.713+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:10:56.714+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:10:56.714+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:10:57.199+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:10:57.194+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:10:57.201+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:10:57.218+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.514 seconds
[2025-02-12T21:11:27.671+0000] {processor.py:186} INFO - Started process (PID=2065) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:11:27.673+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:11:27.674+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:11:27.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:11:27.998+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:11:27.990+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:11:28.000+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:11:28.025+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.360 seconds
[2025-02-12T21:11:58.116+0000] {processor.py:186} INFO - Started process (PID=2077) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:11:58.117+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:11:58.119+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:11:58.118+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:11:58.450+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:11:58.441+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:11:58.453+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:11:58.471+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.362 seconds
[2025-02-12T21:12:28.852+0000] {processor.py:186} INFO - Started process (PID=2089) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:12:28.854+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:12:28.855+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:12:28.855+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:12:29.315+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:12:29.307+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:12:29.318+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:12:29.334+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.490 seconds
[2025-02-12T21:12:59.416+0000] {processor.py:186} INFO - Started process (PID=2101) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:12:59.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-12T21:12:59.419+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:12:59.419+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:12:59.933+0000] {logging_mixin.py:190} INFO - [2025-02-12T21:12:59.926+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-12T21:12:59.936+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-12T21:12:59.954+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.544 seconds
