[2025-02-12T09:17:55.089+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T09:17:55.109+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_postgres_dag.create_tables manual__2025-02-12T09:17:54.286521+00:00 [queued]>
[2025-02-12T09:17:55.119+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_postgres_dag.create_tables manual__2025-02-12T09:17:54.286521+00:00 [queued]>
[2025-02-12T09:17:55.120+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-12T09:17:55.135+0000] {taskinstance.py:2890} INFO - Executing <Task(SQLExecuteQueryOperator): create_tables> on 2025-02-12 09:17:54.286521+00:00
[2025-02-12T09:17:55.142+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=439) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-12T09:17:55.143+0000] {standard_task_runner.py:72} INFO - Started process 440 to run task
[2025-02-12T09:17:55.143+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'my_***_dag', 'create_tables', 'manual__2025-02-12T09:17:54.286521+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/my_***_dag.py', '--cfg-path', '/tmp/tmpj2xoeri7']
[2025-02-12T09:17:55.145+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask create_tables
[2025-02-12T09:17:55.161+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-12T09:17:55.198+0000] {task_command.py:467} INFO - Running <TaskInstance: my_postgres_dag.create_tables manual__2025-02-12T09:17:54.286521+00:00 [running]> on host f71098a0f948
[2025-02-12T09:17:55.251+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/secrets_masker.py:84 DeprecationWarning: The sensitive_variable_fields option in [admin] has been moved to the sensitive_var_conn_names option in [core] - the old setting has been used, but please update your config.
[2025-02-12T09:17:55.287+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='my_***_dag' AIRFLOW_CTX_TASK_ID='create_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-02-12T09:17:54.286521+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-12T09:17:54.286521+00:00'
[2025-02-12T09:17:55.288+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-12T09:17:55.307+0000] {sql.py:295} INFO - Executing: CREATE TABLE IF NOT EXISTS products (
 product_id varchar(50) PRIMARY KEY,
 name varchar(50),
 category varchar(50),
 price float
);

CREATE TABLE IF NOT EXISTS orders (
order_id varchar(50) PRIMARY KEY,
customer_id varchar(50),
order_date date,
total_amount float
);

CREATE TABLE IF NOT EXISTS order_items (
order_item_id varchar(50) PRIMARY KEY,
order_id varchar(50),
product_id varchar(50),
quantity int,
price float,
PRIMARY KEY(order_item_id),
CONSTRAINT fk_products
FOREIGN KEY(product_id)
REFERENCES products(product_id),
CONSTRAINT fk_orders
FOREIGN KEY(order_id)
REFERENCES orders(order_id)
);
[2025-02-12T09:17:55.316+0000] {base.py:84} INFO - Retrieving connection '***'
[2025-02-12T09:17:55.330+0000] {base.py:84} INFO - Retrieving connection '***'
[2025-02-12T09:17:55.335+0000] {sql.py:511} INFO - Running statement: CREATE TABLE IF NOT EXISTS products (
 product_id varchar(50) PRIMARY KEY,
 name varchar(50),
 category varchar(50),
 price float
);

CREATE TABLE IF NOT EXISTS orders (
order_id varchar(50) PRIMARY KEY,
customer_id varchar(50),
order_date date,
total_amount float
);

CREATE TABLE IF NOT EXISTS order_items (
order_item_id varchar(50) PRIMARY KEY,
order_id varchar(50),
product_id varchar(50),
quantity int,
price float,
PRIMARY KEY(order_item_id),
CONSTRAINT fk_products
FOREIGN KEY(product_id)
REFERENCES products(product_id),
CONSTRAINT fk_orders
FOREIGN KEY(order_id)
REFERENCES orders(order_id)
);, parameters: None
[2025-02-12T09:17:55.356+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 301, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 516, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidTableDefinition: multiple primary keys for table "order_items" are not allowed
LINE 21: PRIMARY KEY(order_item_id),
         ^

[2025-02-12T09:17:55.366+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=my_***_dag, task_id=create_tables, run_id=manual__2025-02-12T09:17:54.286521+00:00, execution_date=20250212T091754, start_date=20250212T091755, end_date=20250212T091755
[2025-02-12T09:17:55.393+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-12T09:17:55.394+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task create_tables (multiple primary keys for table "order_items" are not allowed
LINE 21: PRIMARY KEY(order_item_id),
         ^
; 440)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 301, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 516, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidTableDefinition: multiple primary keys for table "order_items" are not allowed
LINE 21: PRIMARY KEY(order_item_id),
         ^

[2025-02-12T09:17:55.439+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-12T09:17:55.456+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-12T09:17:55.459+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
