[2025-02-13T01:14:51.946+0000] {processor.py:186} INFO - Started process (PID=2116) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:14:51.947+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:14:51.959+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:14:51.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:14:55.298+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:14:55.154+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:14:55.408+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:14:55.571+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 3.659 seconds
[2025-02-13T01:15:25.765+0000] {processor.py:186} INFO - Started process (PID=2144) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:15:25.766+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:15:25.769+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:15:25.768+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:15:26.392+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:15:26.387+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:15:26.393+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:15:26.417+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.661 seconds
[2025-02-13T01:15:56.736+0000] {processor.py:186} INFO - Started process (PID=2156) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:15:56.737+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:15:56.738+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:15:56.738+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:15:57.083+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:15:57.075+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:15:57.084+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:15:57.104+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.377 seconds
[2025-02-13T01:16:27.422+0000] {processor.py:186} INFO - Started process (PID=2168) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:16:27.423+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:16:27.425+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:16:27.424+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:16:28.048+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:16:28.042+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:16:28.051+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:16:28.082+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.668 seconds
[2025-02-13T01:16:58.665+0000] {processor.py:186} INFO - Started process (PID=2180) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:16:58.666+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:16:58.668+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:16:58.668+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:16:59.227+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:16:59.222+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:16:59.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:16:59.246+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.588 seconds
[2025-02-13T01:17:29.664+0000] {processor.py:186} INFO - Started process (PID=2192) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:17:29.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:17:29.668+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:17:29.667+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:17:30.196+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:17:30.189+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:17:30.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:17:30.214+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.557 seconds
[2025-02-13T01:18:00.691+0000] {processor.py:186} INFO - Started process (PID=2204) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:18:00.692+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:18:00.694+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:18:00.694+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:18:01.180+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:18:01.173+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:18:01.183+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:18:01.199+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.515 seconds
[2025-02-13T01:18:31.702+0000] {processor.py:186} INFO - Started process (PID=2216) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:18:31.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:18:31.706+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:18:31.705+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:18:32.227+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:18:32.219+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:18:32.229+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:18:32.246+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.551 seconds
[2025-02-13T01:19:02.795+0000] {processor.py:186} INFO - Started process (PID=2228) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:19:02.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:19:02.798+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:19:02.798+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:19:03.149+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:19:03.144+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:19:03.152+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:19:03.171+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.383 seconds
[2025-02-13T01:19:33.616+0000] {processor.py:186} INFO - Started process (PID=2240) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:19:33.618+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:19:33.620+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:19:33.620+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:19:34.204+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:19:34.197+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:19:34.206+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:19:34.227+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.624 seconds
[2025-02-13T01:20:04.658+0000] {processor.py:186} INFO - Started process (PID=2252) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:20:04.659+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:20:04.661+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:20:04.661+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:20:05.154+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:20:05.148+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:20:05.157+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:20:05.179+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.529 seconds
[2025-02-13T01:20:35.607+0000] {processor.py:186} INFO - Started process (PID=2264) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:20:35.608+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:20:35.610+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:20:35.610+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:20:36.171+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:20:36.166+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:20:36.173+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:20:36.189+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.588 seconds
[2025-02-13T01:21:06.564+0000] {processor.py:186} INFO - Started process (PID=2276) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:21:06.565+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:21:06.568+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:21:06.567+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:21:07.123+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:21:07.116+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:21:07.125+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:21:07.147+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.592 seconds
[2025-02-13T01:21:37.546+0000] {processor.py:186} INFO - Started process (PID=2288) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:21:37.547+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:21:37.549+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:21:37.548+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:21:38.065+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:21:38.058+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:21:38.068+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:21:38.089+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.550 seconds
[2025-02-13T01:22:08.485+0000] {processor.py:186} INFO - Started process (PID=2300) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:22:08.487+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:22:08.488+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:22:08.488+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:22:09.025+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:22:09.018+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:22:09.027+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:22:09.049+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.571 seconds
[2025-02-13T01:22:39.517+0000] {processor.py:186} INFO - Started process (PID=2312) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:22:39.518+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:22:39.520+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:22:39.519+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:22:40.042+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:22:40.035+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:22:40.045+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:22:40.062+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.552 seconds
[2025-02-13T01:23:10.485+0000] {processor.py:186} INFO - Started process (PID=2324) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:23:10.486+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:23:10.488+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:23:10.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:23:10.980+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:23:10.974+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:23:10.983+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:23:11.001+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.524 seconds
[2025-02-13T01:23:41.557+0000] {processor.py:186} INFO - Started process (PID=2336) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:23:41.558+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:23:41.559+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:23:41.559+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:23:42.043+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:23:42.037+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:23:42.045+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:23:42.065+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.516 seconds
[2025-02-13T01:24:12.543+0000] {processor.py:186} INFO - Started process (PID=2348) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:24:12.545+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:24:12.546+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:24:12.546+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:24:13.027+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:24:13.022+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:24:13.029+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:24:13.048+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.511 seconds
[2025-02-13T01:24:43.470+0000] {processor.py:186} INFO - Started process (PID=2360) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:24:43.472+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:24:43.474+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:24:43.474+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:24:44.011+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:24:44.005+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:24:44.013+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:24:44.030+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.568 seconds
[2025-02-13T01:25:14.650+0000] {processor.py:186} INFO - Started process (PID=2372) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:25:14.651+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:25:14.653+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:25:14.652+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:25:15.199+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:25:15.191+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:25:15.202+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:25:15.228+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.586 seconds
[2025-02-13T01:25:45.697+0000] {processor.py:186} INFO - Started process (PID=2384) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:25:45.698+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:25:45.700+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:25:45.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:25:46.198+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:25:46.191+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:25:46.201+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:25:46.223+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.532 seconds
[2025-02-13T01:26:16.654+0000] {processor.py:186} INFO - Started process (PID=2396) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:26:16.655+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:26:16.657+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:26:16.657+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:26:17.164+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:26:17.156+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:26:17.166+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:26:17.189+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.544 seconds
[2025-02-13T01:26:47.448+0000] {processor.py:186} INFO - Started process (PID=2411) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:26:47.450+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:26:47.452+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:26:47.451+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:26:47.967+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:26:47.962+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:26:47.969+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:26:47.985+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.544 seconds
[2025-02-13T01:27:18.444+0000] {processor.py:186} INFO - Started process (PID=2423) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:27:18.445+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:27:18.447+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:27:18.446+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:27:19.006+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:27:19.000+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:27:19.008+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:27:19.024+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.588 seconds
[2025-02-13T01:27:49.477+0000] {processor.py:186} INFO - Started process (PID=2435) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:27:49.479+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:27:49.481+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:27:49.481+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:27:49.811+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:27:49.804+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:27:49.814+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:27:49.837+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.366 seconds
[2025-02-13T01:28:20.247+0000] {processor.py:186} INFO - Started process (PID=2447) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:28:20.248+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:28:20.250+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:28:20.250+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:28:20.753+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:28:20.745+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:28:20.755+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:28:20.775+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.535 seconds
[2025-02-13T01:28:51.202+0000] {processor.py:186} INFO - Started process (PID=2459) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:28:51.203+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:28:51.205+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:28:51.204+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:28:51.689+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:28:51.682+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:28:51.691+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:28:51.712+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.517 seconds
[2025-02-13T01:29:22.235+0000] {processor.py:186} INFO - Started process (PID=2471) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:29:22.237+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:29:22.238+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:29:22.238+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:29:22.714+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:29:22.707+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:29:22.717+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:29:22.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.511 seconds
[2025-02-13T01:29:53.231+0000] {processor.py:186} INFO - Started process (PID=2483) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:29:53.232+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:29:53.234+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:29:53.234+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:29:53.733+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:29:53.726+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:29:53.735+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:29:53.758+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.536 seconds
[2025-02-13T01:30:24.145+0000] {processor.py:186} INFO - Started process (PID=2495) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:30:24.146+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:30:24.148+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:30:24.148+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:30:24.676+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:30:24.670+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:30:24.678+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:30:24.699+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.562 seconds
[2025-02-13T01:30:54.844+0000] {processor.py:186} INFO - Started process (PID=2507) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:30:54.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:30:54.847+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:30:54.847+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:30:55.345+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:30:55.338+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:30:55.348+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:30:55.364+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.528 seconds
[2025-02-13T01:31:25.783+0000] {processor.py:186} INFO - Started process (PID=2519) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:31:25.785+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:31:25.786+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:31:25.786+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:31:26.250+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:31:26.243+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:31:26.252+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:31:26.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.499 seconds
[2025-02-13T01:31:56.741+0000] {processor.py:186} INFO - Started process (PID=2531) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:31:56.742+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:31:56.744+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:31:56.743+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:31:57.261+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:31:57.254+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:31:57.264+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:31:57.286+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.552 seconds
[2025-02-13T01:32:27.742+0000] {processor.py:186} INFO - Started process (PID=2543) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:32:27.743+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:32:27.745+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:32:27.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:32:28.257+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:32:28.251+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:32:28.260+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:32:28.280+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.545 seconds
[2025-02-13T01:32:58.702+0000] {processor.py:186} INFO - Started process (PID=2555) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:32:58.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:32:58.705+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:32:58.704+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:32:59.298+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:32:59.292+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:32:59.300+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:32:59.319+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.624 seconds
[2025-02-13T01:33:29.767+0000] {processor.py:186} INFO - Started process (PID=2567) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:33:29.768+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:33:29.770+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:33:29.769+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:33:30.101+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:33:30.094+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:33:30.103+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:33:30.121+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.361 seconds
[2025-02-13T01:34:00.503+0000] {processor.py:186} INFO - Started process (PID=2579) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:34:00.504+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:34:00.506+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:34:00.506+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:34:00.983+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:34:00.977+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:34:00.985+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:34:01.002+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.507 seconds
[2025-02-13T01:34:31.094+0000] {processor.py:186} INFO - Started process (PID=2591) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:34:31.096+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:34:31.097+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:34:31.097+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:34:31.618+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:34:31.611+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:34:31.621+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:34:31.639+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.553 seconds
[2025-02-13T01:35:01.706+0000] {processor.py:186} INFO - Started process (PID=2603) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:35:01.707+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:35:01.709+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:35:01.709+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:35:02.209+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:35:02.202+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:35:02.211+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:35:02.231+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.532 seconds
[2025-02-13T01:35:32.639+0000] {processor.py:186} INFO - Started process (PID=2615) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:35:32.640+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:35:32.641+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:35:32.641+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:35:33.118+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:35:33.111+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:35:33.120+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:35:33.141+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.510 seconds
[2025-02-13T01:36:03.659+0000] {processor.py:186} INFO - Started process (PID=2627) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:36:03.661+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:36:03.663+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:36:03.662+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:36:04.180+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:36:04.172+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:36:04.182+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:36:04.196+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.545 seconds
[2025-02-13T01:36:34.682+0000] {processor.py:186} INFO - Started process (PID=2639) to work on /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:36:34.684+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/populate_data_dag.py for tasks to queue
[2025-02-13T01:36:34.686+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:36:34.685+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:36:35.170+0000] {logging_mixin.py:190} INFO - [2025-02-13T01:36:35.163+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/populate_data_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/populate_data_dag.py", line 20, in <module>
    x
NameError: name 'x' is not defined
[2025-02-13T01:36:35.173+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/populate_data_dag.py
[2025-02-13T01:36:35.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/populate_data_dag.py took 0.514 seconds
