[2025-02-13T03:53:06.329+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T03:53:06.352+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table_postgres_dag.create_tables_model manual__2025-02-13T03:53:03.904305+00:00 [queued]>
[2025-02-13T03:53:06.363+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table_postgres_dag.create_tables_model manual__2025-02-13T03:53:03.904305+00:00 [queued]>
[2025-02-13T03:53:06.364+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-13T03:53:06.380+0000] {taskinstance.py:2890} INFO - Executing <Task(SQLExecuteQueryOperator): create_tables_model> on 2025-02-13 03:53:03.904305+00:00
[2025-02-13T03:53:06.392+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=935) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-13T03:53:06.390+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'create_table_***_dag', 'create_tables_model', 'manual__2025-02-13T03:53:03.904305+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/create_table_***_dag.py', '--cfg-path', '/tmp/tmpoautxbbm']
[2025-02-13T03:53:06.394+0000] {standard_task_runner.py:72} INFO - Started process 939 to run task
[2025-02-13T03:53:06.394+0000] {standard_task_runner.py:105} INFO - Job 2: Subtask create_tables_model
[2025-02-13T03:53:06.412+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-13T03:53:06.454+0000] {task_command.py:467} INFO - Running <TaskInstance: create_table_postgres_dag.create_tables_model manual__2025-02-13T03:53:03.904305+00:00 [running]> on host 1202205ac05f
[2025-02-13T03:53:06.746+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/secrets_masker.py:84 DeprecationWarning: The sensitive_variable_fields option in [admin] has been moved to the sensitive_var_conn_names option in [core] - the old setting has been used, but please update your config.
[2025-02-13T03:53:06.779+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='create_table_***_dag' AIRFLOW_CTX_TASK_ID='create_tables_model' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T03:53:03.904305+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T03:53:03.904305+00:00'
[2025-02-13T03:53:06.780+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-13T03:53:06.819+0000] {sql.py:295} INFO - Executing: CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS model;

CREATE TABLE IF NOT EXISTS model.products (
 product_id varchar(50) PRIMARY KEY,
 name varchar(50),
 category varchar(50),
 price float
);

CREATE TABLE IF NOT EXISTS model.orders (
order_id varchar(50) PRIMARY KEY,
customer_id varchar(50),
order_date date,
total_amount float
);

CREATE TABLE IF NOT EXISTS model.order_items (
order_item_id varchar(50) PRIMARY KEY,
order_id varchar(50),
product_id varchar(50),
quantity int,
price float,
CONSTRAINT fk_products
FOREIGN KEY(product_id)
REFERENCES model.products(product_id),
CONSTRAINT fk_orders
FOREIGN KEY(order_id)
REFERENCES model.orders(order_id)
);
[2025-02-13T03:53:06.829+0000] {base.py:84} INFO - Retrieving connection '***'
[2025-02-13T03:53:06.845+0000] {base.py:84} INFO - Retrieving connection '***'
[2025-02-13T03:53:06.850+0000] {sql.py:511} INFO - Running statement: CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS model;

CREATE TABLE IF NOT EXISTS model.products (
 product_id varchar(50) PRIMARY KEY,
 name varchar(50),
 category varchar(50),
 price float
);

CREATE TABLE IF NOT EXISTS model.orders (
order_id varchar(50) PRIMARY KEY,
customer_id varchar(50),
order_date date,
total_amount float
);

CREATE TABLE IF NOT EXISTS model.order_items (
order_item_id varchar(50) PRIMARY KEY,
order_id varchar(50),
product_id varchar(50),
quantity int,
price float,
CONSTRAINT fk_products
FOREIGN KEY(product_id)
REFERENCES model.products(product_id),
CONSTRAINT fk_orders
FOREIGN KEY(order_id)
REFERENCES model.orders(order_id)
);, parameters: None
[2025-02-13T03:53:06.877+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 301, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 516, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_namespace_nspname_index"
DETAIL:  Key (nspname)=(raw) already exists.

[2025-02-13T03:53:06.889+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=create_table_***_dag, task_id=create_tables_model, run_id=manual__2025-02-13T03:53:03.904305+00:00, execution_date=20250213T035303, start_date=20250213T035306, end_date=20250213T035306
[2025-02-13T03:53:06.921+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-13T03:53:06.922+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 2 for task create_tables_model (duplicate key value violates unique constraint "pg_namespace_nspname_index"
DETAIL:  Key (nspname)=(raw) already exists.
; 939)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 301, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 516, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_namespace_nspname_index"
DETAIL:  Key (nspname)=(raw) already exists.

[2025-02-13T03:53:06.971+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-13T03:53:06.997+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-13T03:53:07.002+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
