[2025-02-13T08:25:03.926+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T08:25:03.948+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transform_data_dag.dbt_run manual__2025-02-13T08:24:55.868541+00:00 [queued]>
[2025-02-13T08:25:03.960+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transform_data_dag.dbt_run manual__2025-02-13T08:24:55.868541+00:00 [queued]>
[2025-02-13T08:25:03.961+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-13T08:25:03.976+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): dbt_run> on 2025-02-13 08:24:55.868541+00:00
[2025-02-13T08:25:03.982+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6018) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-13T08:25:03.983+0000] {standard_task_runner.py:72} INFO - Started process 6019 to run task
[2025-02-13T08:25:03.982+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'transform_data_dag', 'dbt_run', 'manual__2025-02-13T08:24:55.868541+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/transform_data_dag.py', '--cfg-path', '/tmp/tmpwui77ael']
[2025-02-13T08:25:03.985+0000] {standard_task_runner.py:105} INFO - Job 73: Subtask dbt_run
[2025-02-13T08:25:04.003+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-13T08:25:04.036+0000] {task_command.py:467} INFO - Running <TaskInstance: transform_data_dag.dbt_run manual__2025-02-13T08:24:55.868541+00:00 [running]> on host 89bb8c6379b5
[2025-02-13T08:25:04.095+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/log/secrets_masker.py:84 DeprecationWarning: The sensitive_variable_fields option in [admin] has been moved to the sensitive_var_conn_names option in [core] - the old setting has been used, but please update your config.
[2025-02-13T08:25:04.126+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='transform_data_dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T08:24:55.868541+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T08:24:55.868541+00:00'
[2025-02-13T08:25:04.127+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-13T08:25:04.144+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-13T08:25:04.146+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/airflow/dags/dbt/***_project && dbt run']
[2025-02-13T08:25:04.153+0000] {subprocess.py:99} INFO - Output:
[2025-02-13T08:25:06.504+0000] {subprocess.py:106} INFO - [0m08:25:06  Running with dbt=1.8.7
[2025-02-13T08:25:06.834+0000] {subprocess.py:106} INFO - [0m08:25:06  Registered adapter: ***=1.9.0
[2025-02-13T08:25:07.572+0000] {subprocess.py:106} INFO - [0m08:25:07  Found 6 models, 2 data tests, 3 sources, 429 macros
[2025-02-13T08:25:07.576+0000] {subprocess.py:106} INFO - [0m08:25:07
[2025-02-13T08:25:07.704+0000] {subprocess.py:106} INFO - [0m08:25:07  Concurrency: 1 threads (target='dev')
[2025-02-13T08:25:07.705+0000] {subprocess.py:106} INFO - [0m08:25:07
[2025-02-13T08:25:07.782+0000] {subprocess.py:106} INFO - [0m08:25:07  1 of 3 START sql incremental model model.order_items ........................... [RUN]
[2025-02-13T08:25:08.039+0000] {subprocess.py:106} INFO - [0m08:25:08  1 of 3 OK created sql incremental model model.order_items ...................... [[32mINSERT 0 0[0m in 0.25s]
[2025-02-13T08:25:08.042+0000] {subprocess.py:106} INFO - [0m08:25:08  2 of 3 START sql incremental model model.orders ................................ [RUN]
[2025-02-13T08:25:08.159+0000] {subprocess.py:106} INFO - [0m08:25:08  2 of 3 ERROR creating sql incremental model model.orders ....................... [[31mERROR[0m in 0.11s]
[2025-02-13T08:25:08.162+0000] {subprocess.py:106} INFO - [0m08:25:08  3 of 3 START sql incremental model model.products .............................. [RUN]
[2025-02-13T08:25:08.281+0000] {subprocess.py:106} INFO - [0m08:25:08  3 of 3 ERROR creating sql incremental model model.products ..................... [[31mERROR[0m in 0.12s]
[2025-02-13T08:25:08.301+0000] {subprocess.py:106} INFO - [0m08:25:08
[2025-02-13T08:25:08.302+0000] {subprocess.py:106} INFO - [0m08:25:08  Finished running 3 incremental models in 0 hours 0 minutes and 0.72 seconds (0.72s).
[2025-02-13T08:25:08.384+0000] {subprocess.py:106} INFO - [0m08:25:08
[2025-02-13T08:25:08.385+0000] {subprocess.py:106} INFO - [0m08:25:08  [31mCompleted with 2 errors and 0 warnings:[0m
[2025-02-13T08:25:08.387+0000] {subprocess.py:106} INFO - [0m08:25:08
[2025-02-13T08:25:08.388+0000] {subprocess.py:106} INFO - [0m08:25:08    Database Error in model orders (models/cleansed/orders.sql)
[2025-02-13T08:25:08.388+0000] {subprocess.py:106} INFO -   multiple primary keys for table "orders" are not allowed
[2025-02-13T08:25:08.389+0000] {subprocess.py:106} INFO -   compiled code at target/run/***_project/models/cleansed/orders.sql
[2025-02-13T08:25:08.389+0000] {subprocess.py:106} INFO - [0m08:25:08
[2025-02-13T08:25:08.390+0000] {subprocess.py:106} INFO - [0m08:25:08    Database Error in model products (models/cleansed/products.sql)
[2025-02-13T08:25:08.390+0000] {subprocess.py:106} INFO -   multiple primary keys for table "products" are not allowed
[2025-02-13T08:25:08.390+0000] {subprocess.py:106} INFO -   compiled code at target/run/***_project/models/cleansed/products.sql
[2025-02-13T08:25:08.391+0000] {subprocess.py:106} INFO - [0m08:25:08
[2025-02-13T08:25:08.391+0000] {subprocess.py:106} INFO - [0m08:25:08  Done. PASS=1 WARN=0 ERROR=2 SKIP=0 TOTAL=3
[2025-02-13T08:25:09.113+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-02-13T08:25:09.125+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-13T08:25:09.129+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=transform_data_dag, task_id=dbt_run, run_id=manual__2025-02-13T08:24:55.868541+00:00, execution_date=20250213T082455, start_date=20250213T082503, end_date=20250213T082509
[2025-02-13T08:25:09.157+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-13T08:25:09.158+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 73 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 6019)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-13T08:25:09.192+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-13T08:25:09.213+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-13T08:25:09.219+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
